"""
Given strings S and T, find the minimum (contiguous) substring W of S, so that T is a subsequence of W.
If there is no such window in S that covers all characters in T, return the empty string "". 
If there are multiple such minimum-length windows, return the one with the left-most starting index.

Example 1
Input：S="jmeqksfrsdcmsiwvaovztaqenprpvnbstl"，T="u"
Output：""
Explanation： unable to match

Example 2
Input：S = "abcdebdde"， T = "bde"
Output："bcde"
Explanation："bcde" is the answer and "deb" is not a smaller window because the elements of T in the window must occur in order.

https://www.lintcode.com/en/old/problem/minimum-window-subsequence/
"""
import time
# from memory_profiler import memory_usage
from memory_profiler import profile

def minimum_window_subsequence_recursion_wrong(str_S, str_T, str_output=""):
    # WRONG! Returns only the first, not the shortest.
    if(str_T == ""):
        return(str_output)
    if(str_S == "" and str_T != ""):
        return("")
    if(str_S[0] != str_T[0]):
        if(str_output == ""):
            return(minimum_window_subsequence_recursion_wrong(str_S[1:], str_T, str_output))
        else:
            return(minimum_window_subsequence_recursion_wrong(str_S[1:], str_T, str_output + str_S[0]))
    else:
        return(minimum_window_subsequence_recursion_wrong(str_S[1:], str_T[1:], str_output + str_T[0]))

def test_substring(string, substring):
    # Tests if all the characters in the substring are present in the string in order
    while(string != "" and substring !=""):
        if(substring[0] == string[0]):
            substring = substring[1:]
        string = string[1:]
    if(substring == ""):
        return(True)
    return(False)

# @profile
def minimum_window_subsequence_brute_force(str_S, str_T):
    if(any(string not in str_S for string in str_T)):
        return("")
    str_start = str_T[0]
    str_end = str_T[-1]
    list_str_start_indices = [index for index in range(len(str_S)) if str_S[index] == str_start]
    list_str_end_indices = [index for index in range(len(str_S)) if str_S[index] == str_end]

    list_tuples_start_to_end = sorted(
        [
            (index_start, index_end) 
            for index_start in list_str_start_indices 
            for index_end in list_str_end_indices 
                if 
                    index_start < index_end
                    and index_end - index_start > len(str_T) - 2
        ], 
        key=lambda x: x[1] - x[0]
    )
    
    for index_start, index_end in list_tuples_start_to_end:
        if(test_substring(str_S[index_start - 1: index_end], str_T[1:-1])):
            return(str_S[index_start: index_end + 1])
    return("")

# @profile
def minimum_window_subsequence_recursion(str_S, str_T):
    def memoize(f):
        memo = {}
        def memoizer(*args, **kwargs):
            key = str(args) + str(kwargs)
            if(key not in memo):
                memo[key] = f(*args, **kwargs)
            # print(len(memo))
            return(memo[key])
        return(memoizer)

    # @memoize
    def recurse(str_S, str_T, str_output=""):
        if(str_T == ""):
            return(str_output)
        if(str_S == "" and str_T != ""):
            return("")
        if(str_S[0] != str_T[0]):
            if(str_output == ""):
                return(recurse(str_S[1:], str_T, str_output))
            else:
                return(recurse(str_S[1:], str_T, str_output + str_S[0]))
        else:
            return(recurse(str_S[1:], str_T[1:], str_output + str_T[0]))
    
    str_start = str_T[0]
    list_subsequence_strings = [recurse(str_S[index:], str_T) for index in range(len(str_S)) if str_S[index] == str_start]
    list_subsequence_strings = [string for string in list_subsequence_strings if string != ""]

    str_output = min(list_subsequence_strings)
    if(str_output == []):
        return("")
    return(str_output)


if __name__ == "__main__":
    # print(minimum_window_subsequence_recursion_wrong("abcdebdde", "bd`e"))
    # print(minimum_window_subsequence_recursion_wrong("abbbcdeaaabbcedbbAbbea", "bbceA"))
    # print(minimum_window_subsequence_recursion_wrong("jmeqksfrsdcmsiwvaovztaqenprpvnbstl", "u"))
    # print(minimum_window_subsequence("abbbcdeaaabbcedbbabbea", "bbcea"))
    # print(minimum_window_subsequence("abcdebdde", "bde"))
    # print(minimum_window_subsequence("224528959", "259"))
    # print(minimum_window_subsequence("aaAbCBDmmaAccdBccCdddDAmBnCdD", "ABCD"))
    # print(minimum_window_subsequence("aaAbCBDmmaAccdBccCdddDAmBnCdDABDCABmmCD", "ABCD"))
    str_S = "aaAbCBDmmaAccdBccCABbCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABbCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABbCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCddddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABbCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABbCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABbCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABbCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDaaAbCBDmmaAccdBccCABCDdddDAmBnCdDABDCABmmCDA"
    str_T = "ABCD"
    time_start = time.time()
    print(minimum_window_subsequence_brute_force(str_S, str_T))
    print("Brute force: {} seconds.".format(time.time() - time_start))
    time_start = time.time()
    print(minimum_window_subsequence_recursion(str_S, str_T))
    print("Recursion: {} seconds.".format(time.time() - time_start))